# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a0af53e3723142820a6d324d7df01b4e9259b6124320015946981267a4e8f62eeff789003d10d125626dd0f6776b1b6008b5c5df5662707be9e0932038478ad

test:
  secret_key_base: 847ee845745386d1faf2d4ae3df23a53d13707c47cec2d36c1564ad0f4a93d21e236c696c18d463975449e1b30aa4672b2d283063620dfbd155a31414da81a14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
